### ISSUE TITLE
Always need to provide image height and width

### ISSUE THREAD

**Issue by AswinPG** [jonathanpeppers/glidex#84]
I am trying to create a staggered layout but while using glidex I cannot get the image size. I need to provide height request and width request manually. What should I do to get correct sizes ?

**Comment by AswinPG** [comment]
Saw same issue so I am closing this

**Comment by jonathanpeppers** [comment]
@AswinPG this has been coming up lately, if I put some docs on the `README` about this, do you think you would have seen it?

**Comment by AswinPG** [comment]
Yes I would have. Is there a workaround for this ?

**Comment by jonathanpeppers** [comment]
It's the same problem I posted here: https://github.com/jonathanpeppers/glidex/issues/10#issuecomment-433109852

Since Glide loads images based on the size of the `ImageView` -- and Xamarin.Forms tends to do layout of the `ImageView` based on the image size, I don't know a way to reconcile this...

If you have some ideas, let me know!

**Comment by AswinPG** [comment]
Sure :) This is a great library by the way. Images that would not load on default forms Image loads easily with glidex. Thanks for this
