### ISSUE TITLE
Not Loading Images

### ISSUE THREAD

**Issue by assaab** [jonathanpeppers/glidex#99]
hello i am using the glidex package and its amazing how it improved my application performance , but unfortunately most of the Embedded resource images are not loaded . I Would like help in fixing this bug my app is performing soo slow without this glidex package. Thank you.

**Comment by jonathanpeppers** [comment]
I'd recommend not using `EmbeddedResource`? The native Glide library doesn't know how to load `EmbeddedResource` because it is a .NET concept, so we have to copy to an intermediate `byte[]` for it to even work.

We have samples that use it, though, it should generally work:

https://github.com/jonathanpeppers/glidex/blob/ca15efd1098ad65ea78e8b791f81dbb6eda92f04/glidex.forms.sample/Forms/Images.cs#L49-L53

Can you add a page to the sample app in this repo and cause the issue?

https://github.com/jonathanpeppers/glidex/tree/main/glidex.forms.sample/Forms

Thanks!

**Comment by assaab** [comment]
Sorry but I didn’t understand how to solve the issue? And you want me to do what?

**Comment by jonathanpeppers** [comment]
Add a new page to the sample app that reproduces your issue?

**Comment by assaab** [comment]
Thank you for your time i removed all my embedded images even though it ruined my whole application because using embedded images fits the image in the control without losing its quality . E.g and imagebutton control can control the size of it imagesource by changing height and width of buttom. This doesn’t happen when images are placed in drawable file in android. Thus i was obliged to reduce image resolution inorder to cha ge its size in the control thus losing its quality. 
I would like you to check the bug related to embedded images in ur package because some of them worked (10% of the images) whereas the rest didn’t load .

**Comment by jonathanpeppers** [comment]
Yes, make a quick page that shows your issue, and I can take a look.

It might be the Java Glide library doesn't know how to load arbitratary `byte[]` of certain images? And there isn't anything we can do about that?

**Comment by assaab** [comment]
I tried to add two files one .xml named EmbbadedImage.xml that have code that call the class ImageResourceExtension to get the embbaded image.
Sorry i am new to git so i dont know if it wokred.
